import test from 'node:test';
import assert from 'node:assert/strict';
import {
  createStudentBackupFingerprint,
  isStudentBackupDirty,
  shouldWarnBeforeUnload,
  studentBackupDataSnapshot,
} from '../src/student-backup-dirty.mjs';

function studentState(overrides = {}) {
  return {
    student: { studentId: '', studentName: '' },
    actual: [],
    quickAverages: {},
    inputModes: {},
    targetAverage: '',
    weighted: true,
    admissionInterests: [],
    activeSemester: '1-1',
    calculated: false,
    goalCalculated: false,
    ...overrides,
  };
}

const isAutoGeneratedRecord = (record) => record.courseId?.startsWith('common-');
const fingerprint = (state) => createStudentBackupFingerprint(state, { isAutoGeneratedRecord });

test('최초 빈 학생 상태는 clean이고 학번·이름 변경은 dirty다', () => {
  const initial = studentState();
  const baseline = fingerprint(initial);
  assert.equal(isStudentBackupDirty(baseline, initial, { isAutoGeneratedRecord }), false);
  assert.equal(isStudentBackupDirty(baseline, studentState({ student: { studentId: '10101', studentName: '' } }), { isAutoGeneratedRecord }), true);
  assert.equal(isStudentBackupDirty(baseline, studentState({ student: { studentId: '', studentName: '김학생' } }), { isAutoGeneratedRecord }), true);
});

test('간편 평균·상세 성적·학점·성취도·목표·학점 가중·관심 대학은 dirty 대상이다', () => {
  const baseline = fingerprint(studentState());
  const cases = [
    studentState({ quickAverages: { '1-1': 2.1 }, inputModes: { '1-1': 'quick' } }),
    studentState({ actual: [{ courseId: 'common-korean-1', semesterId: '1-1', gradeValue: '2', credit: 4 }] }),
    studentState({ actual: [{ courseId: 'music-1', semesterId: '1-1', achievement: 'A', credit: 2, gradingType: 'achievement' }] }),
    studentState({ targetAverage: '2.10' }),
    studentState({ weighted: false }),
    studentState({ admissionInterests: [{ universityId: 'u1', department: '경제학과', admissionName: '일반전형' }] }),
  ];
  cases.forEach((current) => assert.equal(isStudentBackupDirty(baseline, current, { isAutoGeneratedRecord }), true));
});

test('자동 생성된 빈 공통 과목과 일시적 화면 상태는 dirty 대상이 아니다', () => {
  const baseline = fingerprint(studentState());
  const transient = studentState({
    actual: [{ courseId: 'common-korean-1', semesterId: '1-1', gradeValue: '', achievement: '', credit: 4 }],
    activeSemester: '2-1',
    calculated: true,
    goalCalculated: true,
    admissionUi: { admissionViewMode: 'student-record-subject', admissionFilters: { department: '경제' } },
  });
  assert.equal(isStudentBackupDirty(baseline, transient, { isAutoGeneratedRecord }), false);
});

test('현재 상태가 마지막 백업 기준으로 정확히 되돌아오면 다시 clean이다', () => {
  const saved = studentState({ student: { studentId: '10101', studentName: '김학생' }, quickAverages: { '1-1': 2.3 }, inputModes: { '1-1': 'quick' } });
  const baseline = fingerprint(saved);
  const modified = studentState({ ...saved, targetAverage: '1.90' });
  assert.equal(isStudentBackupDirty(baseline, modified, { isAutoGeneratedRecord }), true);
  assert.equal(isStudentBackupDirty(baseline, saved, { isAutoGeneratedRecord }), false);
});

test('성공한 backup·정상 restore·초기화는 각각 새 clean 기준을 만들고 실패한 restore는 기존 기준을 보존한다', () => {
  const initial = studentState();
  const baseline = fingerprint(initial);
  const changed = studentState({ student: { studentId: '10101', studentName: '김학생' } });
  assert.equal(isStudentBackupDirty(baseline, changed, { isAutoGeneratedRecord }), true);

  const successfulBackupBaseline = fingerprint(changed);
  assert.equal(isStudentBackupDirty(successfulBackupBaseline, changed, { isAutoGeneratedRecord }), false);

  const restored = studentState({ quickAverages: { '1-1': 2.2 }, inputModes: { '1-1': 'quick' } });
  const restoreBaseline = fingerprint(restored);
  assert.equal(isStudentBackupDirty(restoreBaseline, restored, { isAutoGeneratedRecord }), false);
  assert.equal(isStudentBackupDirty(restoreBaseline, studentState({ ...restored, targetAverage: '2.0' }), { isAutoGeneratedRecord }), true);

  // 잘못된 파일을 거부했을 때 앱은 changed state/baseline을 바꾸지 않는다.
  assert.equal(isStudentBackupDirty(baseline, changed, { isAutoGeneratedRecord }), true);
  assert.equal(isStudentBackupDirty(fingerprint(initial), initial, { isAutoGeneratedRecord }), false);
});

test('dirty일 때만 beforeunload 경고를 요청한다', () => {
  assert.equal(shouldWarnBeforeUnload(false), false);
  assert.equal(shouldWarnBeforeUnload(true), true);
});

test('스냅샷에는 학생이 보존해야 할 데이터만 있고 UI·파생 계산값은 없다', () => {
  const snapshot = studentBackupDataSnapshot(studentState({
    student: { studentId: '10101', studentName: '김학생' },
    quickAverages: { '1-1': 2.2 },
    activeSemester: '3-1',
    calculated: true,
    goalCalculated: true,
    includeAchievementCourses: true,
  }), { isAutoGeneratedRecord });
  assert.deepEqual(Object.keys(snapshot).sort(), ['actual', 'admissionInterests', 'inputModes', 'quickAverages', 'student', 'targetAverage', 'weighted']);
  assert.equal(Object.hasOwn(snapshot, 'activeSemester'), false);
  assert.equal(Object.hasOwn(snapshot, 'calculated'), false);
});
