import { ACTIVE_ENTRY_YEAR } from './course-catalog.mjs?v=20260914-grading-types2';
import { catalogCourses, saveCatalog, upsertCatalogCourse, disableCatalogCourse, resetCatalogOverrides } from './course-catalog-store.mjs?v=20260914-teacher-store';

const $ = (selector) => document.querySelector(selector);
let courses = catalogCourses();
let editingId = null;
const filters = { year: String(ACTIVE_ENTRY_YEAR), grade: 'all', semester: 'all' };
const makeId = () => `course-${Date.now()}-${Math.random().toString(16).slice(2)}`;
function toast(message) { $('#teacher-toast').textContent = message; clearTimeout(toast.timer); toast.timer = setTimeout(() => { $('#teacher-toast').textContent = ''; }, 2400); }
function filteredCourses() { return courses.filter((course) => String(course.entryYear) === filters.year && (filters.grade === 'all' || String(course.grade) === filters.grade) && (filters.semester === 'all' || String(course.semester) === filters.semester)).sort((a, b) => (a.displayOrder ?? 0) - (b.displayOrder ?? 0) || a.subjectName.localeCompare(b.subjectName, 'ko')); }
function renderFilters() { const years = [...new Set([ACTIVE_ENTRY_YEAR, ...courses.map((course) => Number(course.entryYear))])].sort((a, b) => a - b); $('#filter-year').innerHTML = years.map((year) => `<option value="${year}">${year}학년도 입학생</option>`).join(''); $('#filter-year').value = filters.year; }
function renderList() { const visible = filteredCourses(); $('#course-count').textContent = `${visible.length}개 과목 · 비활성 과목 포함`; $('#course-list').innerHTML = visible.length ? visible.map((course) => `<article class="teacher-course ${course.active !== false && course.enabled !== false ? '' : 'is-inactive'}"><div><strong>${escapeHtml(course.subjectName)}</strong><span>${course.grade}학년 ${course.semester}학기 · ${escapeHtml(course.subjectGroup)} · ${course.credit}학점</span><small>${course.requirement === 'common' ? '공통' : course.requirement === 'elective' ? '선택' : '학교 지정'} · ${course.gradingType} · 순서 ${course.displayOrder ?? 0}</small></div><div class="teacher-course-actions"><span class="status-chip">${course.active !== false && course.enabled !== false ? '개설 ON' : '개설 OFF'}</span><button class="quiet-button" data-edit="${escapeHtml(course.id)}">수정</button><button class="quiet-button" data-disable="${escapeHtml(course.id)}">${course.active !== false ? '비활성화' : '활성화'}</button></div></article>`).join('') : '<p class="empty-state">조건에 맞는 과목이 없습니다.</p>'; }
function escapeHtml(value = '') { return String(value).replace(/[&<>'"]/g, (char) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[char])); }
function openEditor(course = null) { editingId = course?.id ?? null; $('#editor-title').textContent = course ? '과목 수정' : '과목 추가'; $('#course-id').value = course?.id ?? ''; $('#course-year').value = course?.entryYear ?? filters.year; $('#course-grade').value = course?.grade ?? (filters.grade === 'all' ? '1' : filters.grade); $('#course-semester').value = course?.semester ?? (filters.semester === 'all' ? '1' : filters.semester); $('#course-name').value = course?.subjectName ?? ''; $('#course-group').value = course?.subjectGroup ?? ''; $('#course-credit').value = course?.credit ?? 3; $('#course-grading').value = course?.gradingType ?? 'grade'; $('#course-requirement').value = course?.requirement ?? 'elective'; $('#course-order').value = course?.displayOrder ?? courses.length; $('#course-active').checked = course?.active !== false; $('#course-enabled').checked = course?.enabled !== false; $('#course-editor').hidden = false; $('#course-name').focus(); }
function closeEditor() { editingId = null; $('#course-editor').hidden = true; }
function formCourse() { const grade = Number($('#course-grade').value); const semester = Number($('#course-semester').value); const gradingType = $('#course-grading').value; const achievementScale = gradingType === 'grade' ? 'none' : 'a-e'; return { id: editingId || makeId(), entryYear: Number($('#course-year').value), grade, semester, semesterId: `${grade}-${semester}`, subjectName: $('#course-name').value.trim(), subjectGroup: $('#course-group').value.trim(), credit: Number($('#course-credit').value), gradingType, fiveLevelEligible: ['grade','both'].includes(gradingType), achievementOnly: gradingType === 'achievement', achievementScale, curriculumCategory: 'teacher-managed', requirement: $('#course-requirement').value, availability: 'teacher-managed', classConditions: [], autoGenerate: $('#course-requirement').value === 'common' && grade === 1, active: $('#course-active').checked, enabled: $('#course-enabled').checked, displayOrder: Number($('#course-order').value), duplicateSelectionWarning: false }; }
renderFilters(); renderList();
['filter-year','filter-grade','filter-semester'].forEach((id) => $(`#${id}`).addEventListener('change', (event) => { filters[{ 'filter-year':'year','filter-grade':'grade','filter-semester':'semester' }[id]] = event.target.value; renderList(); }));
$('#add-course').addEventListener('click', () => openEditor());
$('#course-list').addEventListener('click', (event) => { const editId = event.target.dataset.edit; const disableId = event.target.dataset.disable; if (editId) openEditor(courses.find((course) => course.id === editId)); if (disableId) { const course = courses.find((item) => item.id === disableId); courses = course && (course.active === false || course.enabled === false) ? upsertCatalogCourse({ ...course, active: true, enabled: true }) : disableCatalogCourse(disableId); renderFilters(); renderList(); toast(`${course?.subjectName ?? '과목'} 개설 상태를 변경했습니다.`); } });
$('#course-form').addEventListener('submit', (event) => { event.preventDefault(); const course = formCourse(); if (!course.subjectName || !course.subjectGroup || !course.entryYear || !course.credit) { toast('과목명·교과군·학점·연도를 확인해 주세요.'); return; } courses = upsertCatalogCourse(course); filters.year = String(course.entryYear); filters.grade = String(course.grade); filters.semester = String(course.semester); renderFilters(); renderList(); closeEditor(); toast('과목 정보를 저장했습니다.'); });
$('#reset-catalog').addEventListener('click', () => { if (!confirm('선생님이 저장한 과목 변경을 모두 지우고 기본 카탈로그로 되돌릴까요?')) return; courses = resetCatalogOverrides(); renderFilters(); renderList(); toast('기본 카탈로그로 되돌렸습니다.'); });
$('#cancel-edit').addEventListener('click', closeEditor); $('#cancel-edit-bottom').addEventListener('click', closeEditor);
